// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./filter";
export * from "./filterPolicy";
export * from "./rateLimit";

// Import resources to register:
import { Filter } from "./filter";
import { FilterPolicy } from "./filterPolicy";
import { RateLimit } from "./rateLimit";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:getambassador.io/v1beta2:Filter":
                return new Filter(name, <any>undefined, { urn })
            case "kubernetes:getambassador.io/v1beta2:FilterPolicy":
                return new FilterPolicy(name, <any>undefined, { urn })
            case "kubernetes:getambassador.io/v1beta2:RateLimit":
                return new RateLimit(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "getambassador.io/v1beta2", _module)
