apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: d63ec4cf-6c25-47fc-a8f4-f0e0578a4b9e
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: 0.1.0
    app.kubernetes.io/name: usersvc
  name: usersvc
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: 0.1.0
      app.kubernetes.io/name: usersvc
  strategy:
    canary:
      canaryService: usersvc-canary
      maxSurge: 1
      stableService: usersvc
      steps:
      - setWeight: 20
      - pause:
          duration: 60
      - setWeight: 40
      - pause:
          duration: 60
      - setWeight: 60
      - pause:
          duration: 60
      - setWeight: 80
      - pause:
          duration: 60
      - setWeight: 100
      - pause:
          duration: 60
      trafficRouting:
        ambassador:
          mappings:
          - usersvc-mapping
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: 0.1.0
        app.kubernetes.io/name: usersvc
    spec:
      containers:
      - command:
        - web
        image: thedevelopnik/es-overview-usersvc:bc4812a3a615b1c1ed9d2d3f3a1978ad1816d873
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 36
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: usersvc
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 18
          periodSeconds: 3
          timeoutSeconds: 2
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 3000
          runAsNonRoot: true
          runAsUser: 1000
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: http
          periodSeconds: 6
          successThreshold: 1
          timeoutSeconds: 1
      securityContext:
        fsGroup: 2000
      serviceAccountName: usersvc
status:
  blueGreen: {}
  canary: {}
