apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: usersvc
  labels:
    app.kubernetes.io/name: usersvc
    app.kubernetes.io/instance: 0.1.0
  annotations:
    getambassador.io/rolloutId: ee7b914d-56f1-4450-8bd1-0c1214464045
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    canary:
      maxSurge: 1
      canaryService: usersvc-canary
      stableService: usersvc
      trafficRouting:
        ambassador:
          mappings:
            - usersvc-mapping
      steps:
        - setWeight: 100
        - pause:
            duration: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: usersvc
      app.kubernetes.io/instance: 0.1.0
  template:
    metadata:
      annotations:
        'getambassador.io/inject-traffic-agent': enabled
      labels:
        app.kubernetes.io/name: usersvc
        app.kubernetes.io/instance: 0.1.0
    spec:
      serviceAccountName: usersvc
      securityContext:
        fsGroup: 2000
      containers:
        - name: usersvc
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
          image: "index.docker.io/thedevelopnik/es-overview-usersvc:d82ba9b8f07aeff63af1f31276a251f15b42ffb6"
          imagePullPolicy: Always
          command:
            - web
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 10
            periodSeconds: 6
            timeoutSeconds: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 18
            periodSeconds: 3
            failureThreshold: 2
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 36
            periodSeconds: 5
            failureThreshold: 5
            timeoutSeconds: 3
            successThreshold: 1
