---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  websvc-mapping
  labels:
    app.kubernetes.io/name: websvc
    app.kubernetes.io/instance: 0.1.0
spec:
  hostname: esdemo.thedevelopnik.com
  prefix: /
  service: "websvc.default:8080"
  resolver: endpoint
